# Generated by Django 4.0.4 on 2022-05-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='post_videos'),
        ),
        migrations.AddField(
            model_name='post',
            name='yt_link',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
