# Generated by Django 4.0.4 on 2022-05-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_video_post_yt_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='yt_link',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
