# Generated by Django 4.0.4 on 2022-05-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_image_alter_post_yt_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ud',
            new_name='id',
        ),
    ]
