# Generated by Django 4.0.4 on 2022-05-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_ud_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userimg',
            field=models.FilePathField(default=None),
            preserve_default=False,
        ),
    ]
