# Generated by Django 4.0.4 on 2022-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=''),
        ),
    ]
