# Generated by Django 4.0.4 on 2022-05-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_post_userimg_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_profile',
        ),
    ]
