# Generated by Django 4.0.4 on 2022-05-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_post_user_post_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
