# Generated by Django 4.0.4 on 2022-05-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_user_profile_post_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='yt_link',
            new_name='yt_id',
        ),
    ]
